

service: cs-service

frameworkVersion: '3'


provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource: "*"
  ecr:
    images:
      llm-ftdc:
        path: ./

  s3:
    csFolder:
      name: ftdc-cs-bucket

package:
  exclude:
    - layers/**


functions:
  process_pdf:
    environment:
      TRANSFORMERS_CACHE: "/tmp"
    image: 
      name: llm-ftdc
    events:
      - s3:
          bucket: csFolder
          event: s3:ObjectCreated:*
    timeout: 600
    memorySize: 1024


# resources:
#   - ${file(resources/data-lake.yml)}


