Parameters:
  TxnBucketName:
    Type: String
    Default: n-ftdc-target-bucket
    Description: Value that will be prefixed to the bucket name

  TxnDatabaseName:
    Type: String
    MinLength: "4"
    Default: "txn_database"
    Description: "Name of the AWS Glue database to contain this CloudFormation template's tables."

Resources:
  TxnDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Description: Glue database to store transaction data
        Name: !Ref TxnDatabaseName

  RunOnceTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: runOnceTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1



  CrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "CrawlerRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: glue-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - glue:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - athena:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: "*"


  TxnCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: txn_crawler
      Role: !GetAtt CrawlerRole.Arn
      Targets:
        S3Targets:
          - Path: "s3://n-ftdc-target-bucket/processedTxns/"
      DatabaseName: !Ref TxnDatabaseName
      TablePrefix: 'txn_'
      SchemaChangePolicy:
        UpdateBehavior: 'UPDATE_IN_DATABASE'
        DeleteBehavior: 'DEPRECATE_IN_DATABASE'






